// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmhicnsgsaamkteaftjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtaGljbnNnc2FhbWt0ZWFmdGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjE4MjUsImV4cCI6MjA2ODU5NzgyNX0.bm3yy10r_afdGiNVIUOUejdaG4ob1sDDZOZHueIeD9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});